services:
  - type: web
    name: citizen-fraud-shield-api
    env: python
    rootDir: backend
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --no-cache-dir -r requirements.txt
    startCommand: python run.py
